apiVersion: apps/v1
kind: Deployment
metadata:
  name: modular-cicd-app
  labels:
    app: modular-cicd-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: modular-cicd-app
  template:
    metadata:
      labels:
        app: modular-cicd-app
    spec:
      containers:
        - name: modular-cicd-app
          image: modular-cicd-app:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
